<?php 
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

    $products = $block->getProductCollection();  
    $listProduct= $block->getLayout()->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
    
    $brand_img = $block->getBrands(); 
    $pub = $block->getmediaurl();  
?>
    <div class="banner-section">
        <img class="banner-img" src="<?= $pub.$brand_img ?>" /> 
    </div>
<?php 
    if ($listProduct->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }

    $pos = $listProduct->getPositioned();


    ?>
    <?php
        if ($listProduct->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }

        $pos = $listProduct->getPositioned();
        ?>

    <?php if (empty($products)) : ?>
        <div class="message info empty"><div><?= /* @noEscape */ $block->escapeHtml(('We can\'t find products matching the selection.')) ?></div></div>
    <?php else : ?>
        <div class="sparsh-brand-toolbar">
        <?= $block->getToolbarHtml() ?>
        <?= $block->getPagerHtml(); ?>
        </div>
        <?php endif ?>


    <div class="brand-product products wrapper <?= /* @noEscape */ $block->escapeHtml($viewMode) ?> products-<?= /* @noEscape */ $block->escapeHtml($viewMode) ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                    <?php foreach ($products as $product) : ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $listProduct->getImage($product, $image);
                                                          
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= /* @noEscape */ $block->escapeUrl($product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($product->getName()) ?>"
                                    href="<?= $block->escapeUrl($product->getProductUrl($product)) ?>"
                                    class="product-item-link">
                                            <?= $block->escapeHtml($product->getName()) ?>
                                               <?= $product->getSku() ?> 
                                    </a>
                                    
                                </strong>
                                
                                <?php
                                $productNameStripped = $listProduct->stripTags($product->getName(), null, true);
                                ?>
                                <?= /* @noEscape */ $block->getPrice($product) ?>
                            
                            </div>
                        </div>
                    <?php endforeach ?>
            </ol>
    </div> 